export const COURSES = [
  {
    id: 'ux-research',
    emoji: '🎨',
    title: 'Advanced UX Research Methods',
    category: 'Design',
    instructor: 'Dr. Kate Lin',
    instructorInitials: 'KL',
    instructorColor: '#2d8a7a',
    thumbBg: '#e1f2ef',
    lessons: 48, hours: 12, rating: 4.9, reviews: 312,
    students: 3420, progress: 72, module: 8, totalModules: 12,
    level: 'Intermediate', price: 0, lastStudied: '2h ago',
    tags: ['UX Research', 'Interviews', 'Usability'],
    description: 'Master the full spectrum of UX research — from guerrilla testing to sophisticated diary studies.',
  },
  {
    id: 'react-node',
    emoji: '💻',
    title: 'Full-Stack React & Node.js',
    category: 'Engineering',
    instructor: 'Alex Chen',
    instructorInitials: 'AC',
    instructorColor: '#3a6ea8',
    thumbBg: '#e8f0fa',
    lessons: 92, hours: 28, rating: 4.8, reviews: 541,
    students: 5810, progress: 58, module: 14, totalModules: 22,
    level: 'Advanced', price: 29, lastStudied: 'Yesterday',
    tags: ['React', 'Node.js', 'TypeScript', 'REST API'],
    description: 'Build production-grade full-stack apps with React 18, Node.js, TypeScript and PostgreSQL.',
  },
  {
    id: 'growth-marketing',
    emoji: '📈',
    title: 'Growth Marketing Masterclass',
    category: 'Marketing',
    instructor: 'Priya Mehta',
    instructorInitials: 'PM',
    instructorColor: '#c4596a',
    thumbBg: '#faeaec',
    lessons: 36, hours: 9, rating: 4.7, reviews: 208,
    students: 2190, progress: 28, module: 3, totalModules: 10,
    level: 'Beginner', price: 19, lastStudied: '3 days ago',
    tags: ['SEO', 'Paid Ads', 'Email', 'Analytics'],
    description: 'Learn the exact frameworks top growth marketers use to scale from 0 to millions of users.',
  },
  {
    id: 'python-data',
    emoji: '🧠',
    title: 'Data Analysis with Python',
    category: 'Data Science',
    instructor: 'Sam Torres',
    instructorInitials: 'ST',
    instructorColor: '#c8a96e',
    thumbBg: '#e8d5a8',
    lessons: 64, hours: 18, rating: 4.6, reviews: 189,
    students: 1640, progress: 12, module: 2, totalModules: 8,
    level: 'Intermediate', price: 29, lastStudied: 'New this week',
    tags: ['Python', 'Pandas', 'Matplotlib', 'NumPy'],
    description: 'From raw CSV files to polished dashboards — learn pandas, matplotlib and real-world data wrangling.',
  },
  {
    id: 'figma-design',
    emoji: '✏️',
    title: 'Figma for Product Designers',
    category: 'Design',
    instructor: 'Lisa Park',
    instructorInitials: 'LP',
    instructorColor: '#9c5dd1',
    thumbBg: '#f3eafa',
    lessons: 44, hours: 11, rating: 4.9, reviews: 422,
    students: 4100, progress: 0, module: 0, totalModules: 10,
    level: 'Beginner', price: 0, lastStudied: null,
    tags: ['Figma', 'Components', 'Prototyping', 'Design Systems'],
    description: 'Everything you need to go from blank canvas to polished, developer-ready Figma designs.',
  },
  {
    id: 'product-management',
    emoji: '🗺️',
    title: 'Product Management Fundamentals',
    category: 'Product',
    instructor: 'James Wu',
    instructorInitials: 'JW',
    instructorColor: '#2d8a4a',
    thumbBg: '#e1f2e8',
    lessons: 52, hours: 14, rating: 4.5, reviews: 167,
    students: 2890, progress: 0, module: 0, totalModules: 12,
    level: 'Beginner', price: 19, lastStudied: null,
    tags: ['Roadmapping', 'Prioritization', 'Stakeholders', 'Metrics'],
    description: 'Build the strategic and tactical skills to ship products people actually want.',
  },
  {
    id: 'css-mastery',
    emoji: '🎭',
    title: 'CSS Mastery: Modern Layouts',
    category: 'Engineering',
    instructor: 'Nina Ross',
    instructorInitials: 'NR',
    instructorColor: '#c45986',
    thumbBg: '#faeaec',
    lessons: 38, hours: 8, rating: 4.7, reviews: 294,
    students: 3650, progress: 0, module: 0, totalModules: 8,
    level: 'Intermediate', price: 0, lastStudied: null,
    tags: ['CSS Grid', 'Flexbox', 'Animations', 'Variables'],
    description: 'Deep-dive into modern CSS — grid, custom properties, animations and responsive architecture.',
  },
  {
    id: 'agile-scrum',
    emoji: '🔄',
    title: 'Agile & Scrum in Practice',
    category: 'Product',
    instructor: 'Tom Baker',
    instructorInitials: 'TB',
    instructorColor: '#3a6ea8',
    thumbBg: '#e8f0fa',
    lessons: 28, hours: 6, rating: 4.4, reviews: 138,
    students: 1920, progress: 100, module: 8, totalModules: 8,
    level: 'Beginner', price: 0, lastStudied: 'Completed',
    tags: ['Agile', 'Scrum', 'Sprints', 'Retrospectives'],
    description: 'Practical Agile for teams — ceremonies, artefacts, and the mindset shifts that make them work.',
  },
]

export type Course = typeof COURSES[0]

export const CATEGORIES = ['All', 'Design', 'Engineering', 'Marketing', 'Data Science', 'Product']
export const LEVELS = ['All levels', 'Beginner', 'Intermediate', 'Advanced']
